@baseUrl = http://localhost:8000/api

# получение всех датчиков
GET {{baseUrl}}/sensors/
Content-Type: application/json

###

# удаление всех датчиков
DELETE {{baseUrl}}/sensors/
Content-Type: application/json

###

# создание датчика
POST {{baseUrl}}/sensors/
Content-Type: application/json

{
  "name": "ESP32",
  "description": "Датчик на кухне за холодильником"
}

###

# обновление датчика
PATCH {{baseUrl}}/sensors/1/
Content-Type: application/json

{
  "description": "Перенес датчик на балкон"
}

###

# добавление измерения
POST {{baseUrl}}/measurements/
Content-Type: application/json

{
  "sensor": 1,
  "temperature": 22.3
}

###

# добавление измерения с картинкой
POST {{baseUrl}}/measurements/
Content-Type: multipart/form-data; boundary=boundary

--boundary
Content-Disposition: form-data; name="sensor"

1
--boundary
Content-Disposition: form-data; name="temperature"

22.7
--boundary
Content-Disposition: form-data; name="photo"; filename="image.jpg"
Content-Type: image/jpeg

@C:/Users/tase/Desktop/1.jpg
--boundary--

###

# получение информации по датчику
GET {{baseUrl}}/sensors/1/
Content-Type: application/json

###

# тест картинки
GET {{baseUrl}}/media/image.jpg
Content-Type: application/json
